<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="12" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1834" started-at="2017-03-03T21:08:42Z" finished-at="2017-03-03T21:08:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1834" started-at="2017-03-03T21:08:42Z" finished-at="2017-03-03T21:08:44Z">
      <class name="CommandTest.CommandCheckContainsTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="beforeClass" is-config="true" duration-ms="57" started-at="2017-03-03T23:08:42Z" finished-at="2017-03-03T23:08:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="beforeMethod" is-config="true" duration-ms="606" started-at="2017-03-03T23:08:42Z" finished-at="2017-03-03T23:08:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="commandWithTimer_Test_NullArguments()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="commandWithTimer_Test_NullArguments" duration-ms="31" started-at="2017-03-03T23:08:42Z" finished-at="2017-03-03T23:08:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at java.lang.String.contains(Unknown Source)
	at com.klindziuk.framework.CommandCheckContains.run(CommandCheckContains.java:12)
	at com.klindziuk.framework.Command.runWithTimer(Command.java:17)
	at CommandTest.CommandCheckContainsTest.commandWithTimer_Test_NullArguments(CommandCheckContainsTest.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- commandWithTimer_Test_NullArguments -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="beforeMethod" is-config="true" duration-ms="80" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="commandWithTimer_Test_ValidArguments_Negative()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="commandWithTimer_Test_ValidArguments_Negative" duration-ms="10" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at CommandTest.CommandCheckContainsTest.commandWithTimer_Test_ValidArguments_Negative(CommandCheckContainsTest.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- commandWithTimer_Test_ValidArguments_Negative -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="beforeMethod" is-config="true" duration-ms="117" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="commandWithTimer_Test_ValidArguments_Positive()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="commandWithTimer_Test_ValidArguments_Positive" duration-ms="5" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at CommandTest.CommandCheckContainsTest.commandWithTimer_Test_ValidArguments_Positive(CommandCheckContainsTest.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- commandWithTimer_Test_ValidArguments_Positive -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="beforeMethod" is-config="true" duration-ms="99" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="commandWithTimer_Test_ValidSizeParams_EmptyString()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="commandWithTimer_Test_ValidSizeParams_EmptyString" duration-ms="4" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <exception class="com.klindziuk.framework.NotEnoughArgumentException">
            <full-stacktrace>
              <![CDATA[com.klindziuk.framework.NotEnoughArgumentException
	at com.klindziuk.framework.CommandCheckContains.validateParams(CommandCheckContains.java:18)
	at com.klindziuk.framework.CommandCheckContains.run(CommandCheckContains.java:11)
	at com.klindziuk.framework.Command.runWithTimer(Command.java:17)
	at CommandTest.CommandCheckContainsTest.commandWithTimer_Test_ValidSizeParams_EmptyString(CommandCheckContainsTest.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- com.klindziuk.framework.NotEnoughArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- commandWithTimer_Test_ValidSizeParams_EmptyString -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="afterMethod" is-config="true" duration-ms="1" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="beforeMethod" is-config="true" duration-ms="88" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="run_Test_ValidSizeParams_EmptyString()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="run_Test_ValidSizeParams_EmptyString" duration-ms="7" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at java.lang.String.contains(Unknown Source)
	at com.klindziuk.framework.CommandCheckContains.run(CommandCheckContains.java:12)
	at CommandTest.CommandCheckContainsTest.run_Test_ValidSizeParams_EmptyString(CommandCheckContainsTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- run_Test_ValidSizeParams_EmptyString -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="beforeMethod" is-config="true" duration-ms="84" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="run_Test_ValidSizeParams_NullArguments()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="run_Test_ValidSizeParams_NullArguments" duration-ms="8" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at java.lang.String.contains(Unknown Source)
	at com.klindziuk.framework.CommandCheckContains.run(CommandCheckContains.java:12)
	at CommandTest.CommandCheckContainsTest.run_Test_ValidSizeParams_NullArguments(CommandCheckContainsTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- run_Test_ValidSizeParams_NullArguments -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="beforeMethod" is-config="true" duration-ms="100" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="run_Test_ValidSizeParams_ValidArguments_Negative()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="run_Test_ValidSizeParams_ValidArguments_Negative" duration-ms="4" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- run_Test_ValidSizeParams_ValidArguments_Negative -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="beforeMethod" is-config="true" duration-ms="87" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="run_Test_ValidSizeParams_ValidArguments_Positive()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="run_Test_ValidSizeParams_ValidArguments_Positive" duration-ms="5" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- run_Test_ValidSizeParams_ValidArguments_Positive -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="afterMethod" is-config="true" duration-ms="1" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="beforeMethod" is-config="true" duration-ms="83" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="validateParams_Test_NotEnoughArguments()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="validateParams_Test_NotEnoughArguments" duration-ms="2" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <exception class="com.klindziuk.framework.NotEnoughArgumentException">
            <full-stacktrace>
              <![CDATA[com.klindziuk.framework.NotEnoughArgumentException
	at com.klindziuk.framework.CommandCheckContains.validateParams(CommandCheckContains.java:18)
	at CommandTest.CommandCheckContainsTest.validateParams_Test_NotEnoughArguments(CommandCheckContainsTest.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- com.klindziuk.framework.NotEnoughArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateParams_Test_NotEnoughArguments -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="beforeMethod" is-config="true" duration-ms="81" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="validateParams_Test_Null_Document()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="validateParams_Test_Null_Document" duration-ms="3" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method CommandCheckContainsTest.validateParams_Test_Null_Document()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a] should have thrown an exception of type class com.klindziuk.framework.NullDocumentException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method CommandCheckContainsTest.validateParams_Test_Null_Document()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a] should have thrown an exception of type class com.klindziuk.framework.NullDocumentException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1401)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:684)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateParams_Test_Null_Document -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="afterMethod" is-config="true" duration-ms="1" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="beforeMethod" is-config="true" duration-ms="82" started-at="2017-03-03T23:08:43Z" finished-at="2017-03-03T23:08:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="validateParams_Test_Null_params()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="validateParams_Test_Null_params" duration-ms="2" started-at="2017-03-03T23:08:44Z" finished-at="2017-03-03T23:08:44Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method CommandCheckContainsTest.validateParams_Test_Null_params()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a] should have thrown an exception of type class java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method CommandCheckContainsTest.validateParams_Test_Null_params()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a] should have thrown an exception of type class java.lang.NullPointerException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1401)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:684)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateParams_Test_Null_params -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-03-03T23:08:44Z" finished-at="2017-03-03T23:08:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="beforeMethod" is-config="true" duration-ms="79" started-at="2017-03-03T23:08:44Z" finished-at="2017-03-03T23:08:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="validateParams_Test_ToManyArguments()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="validateParams_Test_ToManyArguments" duration-ms="5" started-at="2017-03-03T23:08:44Z" finished-at="2017-03-03T23:08:44Z">
          <exception class="com.klindziuk.framework.ManyArgumentException">
            <full-stacktrace>
              <![CDATA[com.klindziuk.framework.ManyArgumentException
	at com.klindziuk.framework.CommandCheckContains.validateParams(CommandCheckContains.java:21)
	at CommandTest.CommandCheckContainsTest.validateParams_Test_ToManyArguments(CommandCheckContainsTest.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- com.klindziuk.framework.ManyArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateParams_Test_ToManyArguments -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="afterClass" is-config="true" duration-ms="0" started-at="2017-03-03T23:08:44Z" finished-at="2017-03-03T23:08:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:CommandTest.CommandCheckContainsTest@12cc05a]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-03-03T23:08:44Z" finished-at="2017-03-03T23:08:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- CommandTest.CommandCheckContainsTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
